<pre>
<?php //print_r($this->data); die;?>
</pre>

<center>
<h3>
    Отчёт о деятельности менеджеров за период
    с <?
        $date = @date_create($this->data['start']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
    по <?
        $date = @date_create($this->data['end']);
        echo !$date ? '' : $date->format(OSDN_DATE_DISPLAY_FORMAT);
    ?>
</h3>

<table cellspacing="0" cellpadding="5" border="1">
    <tr valign="bottom" align="center">
        <td><b>Менеджер</b></td>
        <td><b>Сумма выполненных заказов <br /> Рубль РФ</b></td>
        <td><b>Сумма добавленных заказов <br /> Рубль РФ</b></td>
        <td><b>Количество <br />просроченных заказов</b></td>
    </tr>
        <?php foreach ($this->data['rows'] as $row) :?>
            <tr>
                <td><?=$row['name']?></td>
                <td align="right"><?=$row['summ_success']?>,00</td>
                <td align="right"><?=$row['summ_added']?>,00</td>
                <td align="right"><?=$row['failed_count']?></td>
            </tr>
        <?php endforeach;?>
</table>
</center>

